In [1]:
import torch
from transformers import BertTokenizer
from transformers import *

In [41]:
!ls

batch_0_cause_mask_0.pt    batch_126_x_sent_2.pt      batch_252_x_sent_0.pt
batch_0_cause_mask_1.pt    batch_126_x_sent_3.pt      batch_252_x_sent_1.pt
batch_0_cause_mask_2.pt    batch_189_cause_mask_0.pt  batch_252_x_sent_2.pt
batch_0_cause_mask_3.pt    batch_189_cause_mask_1.pt  batch_252_x_sent_3.pt
batch_0_hess_0.pt	   batch_189_cause_mask_2.pt  batch_312_cause_mask_0.pt
batch_0_hess_1.pt	   batch_189_cause_mask_3.pt  batch_312_hess_0.pt
batch_0_hess_2.pt	   batch_189_hess_0.pt	      batch_312_x_sent_0.pt
batch_0_hess_3.pt	   batch_189_hess_1.pt	      batch_63_cause_mask_0.pt
batch_0_x_sent_0.pt	   batch_189_hess_2.pt	      batch_63_cause_mask_1.pt
batch_0_x_sent_1.pt	   batch_189_hess_3.pt	      batch_63_cause_mask_2.pt
batch_0_x_sent_2.pt	   batch_189_x_sent_0.pt      batch_63_cause_mask_3.pt
batch_0_x_sent_3.pt	   batch_189_x_sent_1.pt      batch_63_hess_0.pt
batch_126_cause_mask_0.pt  batch_189_x_sent_2.pt      batch_63_hess_1.pt
batch_126_cause_mask_1.pt  batch_189_x_sent_3.pt

In [3]:
batch_0_x_sent_0 = torch.load('batch_0_x_sent_0.pt').squeeze(0)

In [4]:
print(batch_0_x_sent_0)

tensor([  101,  2048,  2308,  2024, 23581,  2096,  3173,  2000,  2175, 14555,
         1012,   102,  1996,  5208,  2024, 17662,  9119,  2096,  3173,  2000,
         2175, 14555,  2044,  2074,  5983,  6265,  1012,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
       device='cuda:0')


In [5]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [6]:
print(tokenizer.convert_ids_to_tokens(batch_0_x_sent_0))
ori_sentence = tokenizer.convert_ids_to_tokens(batch_0_x_sent_0)

['[CLS]', 'two', 'women', 'are', 'embracing', 'while', 'holding', 'to', 'go', 'packages', '.', '[SEP]', 'the', 'sisters', 'are', 'hugging', 'goodbye', 'while', 'holding', 'to', 'go', 'packages', 'after', 'just', 'eating', 'lunch', '.', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']


In [8]:
batch_0_hess_0 = torch.load('batch_0_hess_0.pt').squeeze(0)

In [9]:
print(torch.abs(batch_0_hess_0))
abs_hess = torch.abs(batch_0_hess_0)
no_diag_hess = abs_hess - abs_hess.max() * torch.eye(abs_hess.shape[0], device='cuda:0')

tensor([[0.1106, 0.0314, 0.0179,  ..., 0.0000, 0.0000, 0.0000],
        [0.0314, 0.0855, 0.0656,  ..., 0.0000, 0.0000, 0.0000],
        [0.0179, 0.0656, 0.1476,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
       device='cuda:0')


In [10]:
no_diag_hess

tensor([[-2.5003,  0.0314,  0.0179,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0314, -2.5255,  0.0656,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0179,  0.0656, -2.4633,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ..., -2.6109,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -2.6109,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -2.6109]],
       device='cuda:0')

In [20]:
values, indices = no_diag_hess.max(1)

In [29]:
torch.topk(values, 10)[]

tensor([3535, 3529, 3459, 3580, 3543, 3498, 3547,    3, 1481, 1487],
       device='cuda:0')

In [40]:
pairs = torch.tensor([[i, int(indices[i])] for i in range(indices.shape[0])])
# pairs
# [tokenizer.convert_ids_to_tokens(i) for i in pairs]

In [13]:
# torch.topk(no_diag_hess, 5)

torch.return_types.topk(
values=tensor([[0.1602, 0.1550, 0.1335, 0.1164, 0.1150],
        [0.1623, 0.0946, 0.0881, 0.0861, 0.0788],
        [0.4964, 0.4913, 0.4907, 0.4043, 0.3721],
        ...,
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]], device='cuda:0'),
indices=tensor([[3459, 3535, 3580, 3529, 1411],
        [   3,  112,    5, 3535,  118],
        [   3, 3459, 3535, 1411, 3529],
        ...,
        [   1,    0,    2,    4,    3],
        [   1,    0,    2,    4,    3],
        [   1,    0,    2,    4,    3]], device='cuda:0'))